import { AiRecommendation } from './supabase';
import { SegmentStats } from './cardholder-data';
import { formatIDR, formatCount } from './utils';

export type SegmentData = {
  segment_name: string;
  audience_size: number;
  avg_monthly_spend: number;
  segment_type: string;
  data_source: string;
};

export type MechanicsConfig = {
  campaign_type: string;
  spend_threshold: number;
  reward_type: string;
  reward_value: number;
  reward_cap?: number;       // max reward payout per cardholder (IDR); 0 or undefined = no cap
  duration_days: number;
  eligible_categories: string[];
  target_corridors?: string[];
  travel_timing?: string;
  xb_min_trx?: number;
};

export type Assumptions = {
  take_up_rate: number;
  control_group_pct: number;
  incremental_spend_lift: number;
  avg_transactions_per_month: number;
};

export type SensitivityRow = {
  take_up_rate: number;
  roi: number;
  budget: number;
  activated_cardholders: number;
};

export type SimulationOutput = {
  projected_budget: number;
  projected_uplift_pct: number;
  projected_roi: number;                    // % ROI: (total uplift - budget) / budget * 100
  projected_activated_cardholders: number;
  cost_per_cardholder: number;
  incremental_revenue: number;              // total incremental spend (IDR) across ALL cardholders
  uplift_per_cardholder_idr: number;        // avg incremental spend per cardholder (IDR)
  total_reward_payout: number;
  break_even_spend_lift: number;            // minimum spend lift % needed for ROI >= 0
  break_even_take_up_rate: number;          // alias for break_even_spend_lift (legacy compat)
  sensitivity_data: SensitivityRow[];
  ai_recommendations: AiRecommendation[];
};

const XB_CAMPAIGN_TYPES = new Set([
  'cross_border', 'cross_border_reactivation', 'travel_upsell', 'corridor_push',
]);

// ── reward per cardholder after applying optional cap ─────────────────────────
function calcRewardPerCH(mechanics: MechanicsConfig): number {
  let raw: number;
  if (mechanics.reward_type === 'cashback' || mechanics.reward_type === 'xb_cashback') {
    raw = (mechanics.spend_threshold * mechanics.reward_value) / 100;
  } else if (mechanics.reward_type === 'travel_miles') {
    raw = mechanics.reward_value * 0.5;
  } else {
    raw = mechanics.reward_value;
  }
  if (mechanics.reward_cap && mechanics.reward_cap > 0) {
    return Math.min(raw, mechanics.reward_cap);
  }
  return raw;
}

export function runSimulation(
  segment: SegmentData,
  mechanics: MechanicsConfig,
  assumptions: Assumptions,
  xbStats?: SegmentStats
): SimulationOutput {
  const isXb = XB_CAMPAIGN_TYPES.has(mechanics.campaign_type) || segment.segment_type === 'cross_border';

  // XB campaigns weight take-up by travel probability
  const travelMultiplier = isXb && xbStats
    ? Math.min(1.5, 0.5 + (xbStats.avgTravelProbActive / 100))
    : 1;
  const effectiveTakeUp = isXb
    ? Math.min(50, assumptions.take_up_rate * travelMultiplier)
    : assumptions.take_up_rate;

  const targetAudience = Math.round(segment.audience_size * (1 - assumptions.control_group_pct / 100));
  const activatedCardholders = Math.round(targetAudience * (effectiveTakeUp / 100));

  const rewardPerCardholder = calcRewardPerCH(mechanics);
  const totalRewardPayout = activatedCardholders * rewardPerCardholder;

  // Budget = reward payout only (no hidden admin markup)
  const projectedBudget = totalRewardPayout;

  // ── Incremental spend uplift ───────────────────────────────────────────────
  // Spend uplift is measured across ALL cardholders in the target audience, not just
  // those who "win" the reward — because travel behaviour changes from the campaign
  // communication itself (intent shift), even among non-winning cardholders.
  //
  // We apply a YoY growth signal for XB campaigns as a directional boost.
  const baselineSpend = segment.avg_monthly_spend * (mechanics.duration_days / 30);

  const yoyBoost = isXb && xbStats && xbStats.avgYoY > 0
    ? Math.min(1.3, 1 + xbStats.avgYoY / 200)
    : 1;

  // Uplift per cardholder in IDR (across the full target audience)
  const upliftPerCH = baselineSpend * (assumptions.incremental_spend_lift / 100) * yoyBoost;

  // Total incremental spend = uplift across the full target audience
  const totalIncrementalSpend = targetAudience * upliftPerCH;

  // ── ROI ───────────────────────────────────────────────────────────────────
  // ROI = (total spend uplift − reward budget) / reward budget × 100
  // Numerator: how much incremental travel spend is generated by the whole audience
  // Denominator: the reward cost paid out only to activated cardholders
  const projectedRoi = projectedBudget > 0
    ? ((totalIncrementalSpend - projectedBudget) / projectedBudget) * 100
    : 0;

  const projectedUpliftPct = segment.audience_size > 0
    ? (targetAudience / segment.audience_size) * (assumptions.incremental_spend_lift / 100) * 100
    : 0;

  const costPerCardholder = activatedCardholders > 0 ? projectedBudget / activatedCardholders : 0;

  // Break-even spend lift: minimum lift % so total uplift >= reward budget
  // targetAudience * baselineSpend * (lift/100) * yoyBoost >= projectedBudget
  // → lift >= (projectedBudget / (targetAudience * baselineSpend * yoyBoost)) * 100
  const breakEvenSpendLift =
    targetAudience > 0 && baselineSpend > 0 && yoyBoost > 0
      ? Math.max(0, (projectedBudget / (targetAudience * baselineSpend * yoyBoost)) * 100)
      : 0;

  const sensitivityRates = [5, 10, 15, 20, 25, 30, 40, 50];
  const sensitivityData: SensitivityRow[] = sensitivityRates.map((rate) => {
    const activated = Math.round(targetAudience * (rate / 100));
    const payout = activated * rewardPerCardholder;
    const incrSpend = targetAudience * upliftPerCH;
    const roi = payout > 0 ? ((incrSpend - payout) / payout) * 100 : 0;
    return { take_up_rate: rate, roi, budget: payout, activated_cardholders: activated };
  });

  const recommendations = generateRecommendations(
    segment, mechanics, assumptions,
    {
      projectedRoi,
      projectedBudget,
      activatedCardholders,
      breakEvenSpendLift,
      upliftPerCH,
      rewardPerCardholder,
      targetAudience,
      baselineSpend,
    },
    xbStats
  );

  return {
    projected_budget: projectedBudget,
    projected_uplift_pct: projectedUpliftPct,
    projected_roi: projectedRoi,
    projected_activated_cardholders: activatedCardholders,
    cost_per_cardholder: costPerCardholder,
    incremental_revenue: totalIncrementalSpend,
    uplift_per_cardholder_idr: upliftPerCH,
    total_reward_payout: totalRewardPayout,
    break_even_spend_lift: breakEvenSpendLift,
    break_even_take_up_rate: breakEvenSpendLift,
    sensitivity_data: sensitivityData,
    ai_recommendations: recommendations,
  };
}

function generateRecommendations(
  segment: SegmentData,
  mechanics: MechanicsConfig,
  assumptions: Assumptions,
  metrics: {
    projectedRoi: number;
    projectedBudget: number;
    activatedCardholders: number;
    breakEvenSpendLift: number;
    upliftPerCH: number;
    rewardPerCardholder: number;
    targetAudience: number;
    baselineSpend: number;
  },
  xbStats?: SegmentStats
): AiRecommendation[] {
  const recs: AiRecommendation[] = [];
  const isXb = XB_CAMPAIGN_TYPES.has(mechanics.campaign_type) || segment.segment_type === 'cross_border';

  // ── ROI health ────────────────────────────────────────────────────────────
  if (metrics.projectedRoi < 0) {
    const neededLift = metrics.breakEvenSpendLift.toFixed(1);
    recs.push({
      type: 'warning',
      title: 'Spend Uplift Does Not Cover Reward Budget',
      description: `At ${assumptions.incremental_spend_lift}% spend lift, the total incremental travel spend (${formatIDR(Math.round(metrics.upliftPerCH))}/CH) is less than the reward payout (${formatIDR(Math.round(metrics.rewardPerCardholder))}/CH). You need at least ${neededLift}% spend lift to break even. Try increasing the spend lift assumption, reducing the reward value, or adding a cap.`,
      impact: 'high',
    });
  }

  if (metrics.projectedRoi > 500) {
    recs.push({
      type: 'benchmark',
      title: 'Very High ROI — Verify Spend Lift Assumption',
      description: `A projected ROI of ${metrics.projectedRoi.toFixed(0)}% implies ${assumptions.incremental_spend_lift}% spend lift is unusually high. Cross-check against historical campaign data or YoY trends before finalising budget allocation.`,
      impact: 'medium',
    });
  } else if (metrics.projectedRoi >= 100) {
    recs.push({
      type: 'benchmark',
      title: 'Healthy ROI Projection',
      description: `A ${metrics.projectedRoi.toFixed(0)}% ROI means every IDR of reward budget unlocks ~${((metrics.projectedRoi + 100) / 100).toFixed(1)}× in incremental cardholder spend. This is a strong result for ${isXb ? 'XB' : 'spend stimulation'} campaigns.`,
      impact: 'medium',
    });
  }

  // ── Reward cap suggestion ─────────────────────────────────────────────────
  if (!mechanics.reward_cap && (mechanics.reward_type === 'cashback' || mechanics.reward_type === 'xb_cashback') && metrics.rewardPerCardholder > 0) {
    const suggestedCap = Math.round(metrics.rewardPerCardholder * 0.6 / 10000) * 10000;
    recs.push({
      type: 'optimization',
      title: 'No Reward Cap Set — Budget at Risk',
      description: `Without a cap, each cardholder can earn up to ${formatIDR(Math.round(metrics.rewardPerCardholder))}. A cap of ~${formatIDR(suggestedCap)} (60% of max) protects budget while preserving the incentive for most cardholders. Add a cap in the Mechanics step.`,
      impact: 'high',
    });
  }

  if (mechanics.reward_cap && mechanics.reward_cap > 0 && metrics.rewardPerCardholder > 0) {
    const rawReward = calcRawReward(mechanics);
    const saving = rawReward - mechanics.reward_cap;
    if (saving > 0 && metrics.activatedCardholders > 0) {
      recs.push({
        type: 'suggestion',
        title: 'Reward Cap Active — Budget Protected',
        description: `The ${formatIDR(mechanics.reward_cap)} cap saves up to ${formatIDR(Math.round(saving))} per high-spend cardholder. Across ${formatCount(metrics.activatedCardholders)} activations the potential saving is ${formatIDR(Math.round(saving * metrics.activatedCardholders))} if all cardholders reach uncapped spend.`,
        impact: 'medium',
      });
    }
  }

  // ── Spend threshold vs avg spend ─────────────────────────────────────────
  if (mechanics.spend_threshold > segment.avg_monthly_spend * 1.5) {
    recs.push({
      type: 'optimization',
      title: 'Spend Threshold May Be Too High',
      description: `Threshold ${formatIDR(mechanics.spend_threshold)} is ${((mechanics.spend_threshold / segment.avg_monthly_spend) * 100).toFixed(0)}% of average monthly spend. Lowering to 80–100% of avg spend typically improves take-up by 40% and drives more genuine incremental spend.`,
      impact: 'high',
    });
  }

  if (mechanics.spend_threshold > 0 && mechanics.spend_threshold < segment.avg_monthly_spend * 0.5) {
    recs.push({
      type: 'suggestion',
      title: 'Low Threshold — May Not Drive Incremental Spend',
      description: `Threshold ${formatIDR(mechanics.spend_threshold)} is below 50% of average monthly spend. Most cardholders qualify without changing behaviour, which limits genuine spend uplift and inflates the apparent take-up rate.`,
      impact: 'medium',
    });
  }

  // ── Break-even guidance ───────────────────────────────────────────────────
  if (assumptions.incremental_spend_lift < metrics.breakEvenSpendLift && metrics.breakEvenSpendLift <= 80) {
    recs.push({
      type: 'optimization',
      title: `Raise Spend Lift to ${metrics.breakEvenSpendLift.toFixed(0)}%+ to Break Even`,
      description: `At current reward settings, the campaign needs ${metrics.breakEvenSpendLift.toFixed(1)}% incremental spend lift to cover reward costs. Your assumption is ${assumptions.incremental_spend_lift}%. Adjust the spend lift slider in Assumptions, reduce the reward, or add a cap.`,
      impact: 'high',
    });
  }

  // ── Campaign duration ─────────────────────────────────────────────────────
  if (mechanics.duration_days < 14) {
    recs.push({
      type: 'suggestion',
      title: 'Short Campaign Duration',
      description: isXb
        ? 'XB campaigns under 14 days miss most travel planning windows. 60–90 days aligns with travel cycles and typically achieves 3–4× higher activation.'
        : 'Campaigns under 14 days rarely change cardholder behaviour. 30-day campaigns typically see 2–3× higher take-up.',
      impact: 'medium',
    });
  }

  // ── Control group ─────────────────────────────────────────────────────────
  if (assumptions.control_group_pct < 10) {
    recs.push({
      type: 'suggestion',
      title: 'Small Control Group — Attribution May Be Weak',
      description: 'A holdout below 10% limits your ability to separate campaign-driven uplift from organic growth. 15–20% provides reliable incrementality measurement.',
      impact: 'medium',
    });
  }

  // ── Audience size ─────────────────────────────────────────────────────────
  if (segment.audience_size < 1000) {
    recs.push({
      type: 'suggestion',
      title: 'Small Audience — Statistical Reliability at Risk',
      description: 'Segments below 1,000 cardholders produce high variance in uplift measurement. Consider broadening filters in Step 2 or merging with an adjacent segment.',
      impact: 'low',
    });
  }

  // ── XB-specific ───────────────────────────────────────────────────────────
  if (isXb && xbStats) {
    if (xbStats.activeTravellerPct < 30) {
      recs.push({
        type: 'suggestion',
        title: 'Low Active Traveller Concentration',
        description: `Only ${xbStats.activeTravellerPct}% of this segment are active travellers. Apply Travel Status = "Active Traveller" and a higher propensity decile in Step 2 to concentrate reward budget on proven XB spenders.`,
        impact: 'high',
      });
    }

    if (xbStats.avgYoY < -10) {
      recs.push({
        type: 'warning',
        title: 'Declining XB Spend Trend',
        description: `This segment shows ${xbStats.avgYoY}% YoY decline in XB spend. A reactivation mechanic with a lower threshold (60–70% of avg spend) and urgency timing (next 30 days) is more likely to reverse the trend.`,
        impact: 'high',
      });
    }

    if (xbStats.avgTravelProbActive > 60 && (mechanics.target_corridors?.length ?? 0) === 0) {
      recs.push({
        type: 'optimization',
        title: 'High Travel Probability — Add Corridor Targeting',
        description: `${xbStats.avgTravelProbActive}% of active travellers have high 3-month travel probability. Targeting the top corridor (${xbStats.topCorridor}) with a corridor-specific offer typically improves conversion by 25–40%.`,
        impact: 'medium',
      });
    }

    if ((mechanics.target_corridors?.length ?? 0) > 0) {
      recs.push({
        type: 'benchmark',
        title: 'Corridor-Targeted Campaign',
        description: `Focusing on ${mechanics.target_corridors!.join(', ')} aligns with this segment's travel patterns. Corridor-specific campaigns typically achieve 30–50% higher engagement than broad XB offers.`,
        impact: 'medium',
      });
    }

    if (mechanics.reward_type === 'travel_miles') {
      recs.push({
        type: 'benchmark',
        title: 'Travel Miles — Well Suited for XB Segment',
        description: `Miles rewards resonate strongly with ${xbStats.topPersona} personas. A co-branded airline partnership for the ${xbStats.topCorridor} corridor maximises perceived value without increasing IDR payout.`,
        impact: 'low',
      });
    }

    if ((mechanics.reward_type === 'cashback' || mechanics.reward_type === 'xb_cashback') && !mechanics.reward_cap) {
      recs.push({
        type: 'optimization',
        title: 'XB Cashback Without Cap — High Budget Exposure',
        description: `High-frequency XB travellers can quickly exhaust uncapped cashback budgets. A cap at 50–60% of the uncapped reward is industry standard for XB cashback programs.`,
        impact: 'high',
      });
    }
  }

  if (recs.length === 0) {
    recs.push({
      type: 'benchmark',
      title: 'Well-Balanced Campaign Parameters',
      description: 'Parameters look healthy. Monitor actual take-up in the first week — if activation tracks below 60% of projection, consider lowering the spend threshold.',
      impact: 'low',
    });
  }

  return recs;
}

// helper used only inside recommendations (no cap applied — for displaying raw reward)
function calcRawReward(mechanics: MechanicsConfig): number {
  if (mechanics.reward_type === 'cashback' || mechanics.reward_type === 'xb_cashback') {
    return (mechanics.spend_threshold * mechanics.reward_value) / 100;
  }
  if (mechanics.reward_type === 'travel_miles') return mechanics.reward_value * 0.5;
  return mechanics.reward_value;
}

export function runBudgetOptimization(
  maxBudget: number,
  segment: SegmentData,
  mechanics: MechanicsConfig,
  assumptions: Assumptions
) {
  const rewardPerCH = calcRewardPerCH(mechanics);
  const maxActivatable = rewardPerCH > 0 ? Math.floor(maxBudget / rewardPerCH) : 0;
  const targetAudience = Math.round(segment.audience_size * (1 - assumptions.control_group_pct / 100));
  const recommendedActivated = Math.min(maxActivatable, targetAudience);
  const recommendedTakeUpRate = targetAudience > 0
    ? Math.min(60, Math.max(5, (recommendedActivated / targetAudience) * 100))
    : assumptions.take_up_rate;

  const sim = runSimulation(segment, mechanics, { ...assumptions, take_up_rate: recommendedTakeUpRate });

  return {
    recommended_audience_size: recommendedActivated,
    recommended_take_up_rate: recommendedTakeUpRate,
    recommended_reward_value: mechanics.reward_value,
    projected_roi: sim.projected_roi,
    projected_activated_cardholders: sim.projected_activated_cardholders,
  };
}
